# Generated by Django 4.2.6 on 2023-10-21 10:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="department name"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.department",
                        verbose_name="main department",
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="surname")),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "paternal_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="paternal name"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="position"
                    ),
                ),
                (
                    "salary_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=50,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="salary amount",
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="employment date",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                        verbose_name="department",
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
    ]
